### ISSUE TITLE
The program hooks up when Launched 

### ISSUE THREAD

**Issue by Ahmad138** [Ahmad138/SatRot#20]
It gets hooked up and becomes non responsive the first launch, but after closing and relaunching, the works

**Comment by sonOFsalah-2425778** [comment]
was it from the booting??

**Comment by Ahmad138** [comment]
Not really sure, it started when I tried implementing the threads and timers, Probably. Will have to review it again. You can check and see the code, I commented that part

**Comment by Ahmad138** [comment]
Figured out that it was the webview that was loading really slowly that caused the hooking and eventually crash. will find a better way to implement that.

**Comment by Ahmad138** [comment]
I have resolved the issue. webview was depricated in the recent versions of Qt. After an update and switch to qwebengine, it was resolved. close #20
